# Generated by Django 5.1.4 on 2024-12-17 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_category_options_contact_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Owner',
            new_name='owner',
        ),
    ]
